[project]
name = "universidad_digital_backend"
version = "0.1.0"

[tool.setuptools.packages.find]
include = ["app*"]
exclude = ["tests*"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
branch = true
source = ["app"]
omit = [
	"tests/*",
	"alembic/*",
]

[tool.coverage.report]
fail_under = 90
show_missing = true
skip_covered = true

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I"]
